### ISSUE TITLE
Support for results sections.

### ISSUE THREAD

**Issue by larsbs** [jstayton/jquery-marcopolo#29]
Are there any plans for addding support to sectioned results? Like facebook search, for example (people, places, etc..).

Or is there currently any way of achieving this?

**Comment by jstayton** [comment]
Hi Lorenzo,

No plans to make it a first class citizen, but that's mainly because it's not too difficult with what's available currently.

Use `formatItem` to add a special class to section headers, set `selectable` to exclude those from being selectable, then style them differently from selectable items. Provide a `formatData` callback to splice the data into sections and even insert the section names if they're not already included.

If you need more advanced functionality like collapsing sections, set `hideOnSelect` to `false` and provide an `onSelect` callback that programmatically toggles the section and hides the results on an actual selection.

I've used the above techniques to do almost exactly what you're talking about, and it works great. Let me know if you have any further questions.
