### ISSUE TITLE
formatNoResults not showing

### ISSUE THREAD

**Issue by hanxue** [jstayton/jquery-marcopolo#31]
This is the code I use for autocomplete. Suggested autocomplete works, but when there are no matches, I do not see `No results for <query term>`

```
$('#visitor_company_name').marcoPolo({
    url: '/server/control.php',
    data: {
      mode: 'visit_company_name'
    },
    formatItem: function(data, $item) {
      return data.visitor_company_name;
    },
    onSelect: function(selected_company, $item) {
      $("#visitor_company_name").val(selected_company.visitor_company_name);
    },
    param: 'visitor_company_name',
    minChars: 1,
    delay: 500, // only start autocomplete query after 0.5 seconds
    required: false
  });
```

This is the HTML element from Chrome Inspector

<ol class="mp_list" aria-atomic="true" aria-busy="false" aria-live="polite" id="mp_visitor_company_name_list" role="listbox" style="display: none;"></ol>

Even when I explicitly declare `formatNoResults` in the code

```
formatNoResults: function(q, $item) {
      return '<em>No companies with name <strong>' + q + '</strong>.</em>';
    },
```

I still do not see the results element. The only difference is the CSS style is changed from `display: none` to `display: block`

<ol class="mp_list" aria-atomic="true" aria-busy="false" aria-live="polite" id="mp_visitor_company_name_list" role="listbox" style="display: block;"></ol>

Am I missing anything? I use the exact code for 2 other text input fields and they work fine.

**Comment by jstayton** [comment]
Hi @hanxue,

My guess is the message/element is being added to the DOM, but it's being hidden with CSS somewhere higher up in the hierarchy.

I put together [this example](http://codepen.io/jstayton/pen/PqpdMK) without any CSS. Type in a bunch of random characters, and you'll see the no results message displayed.

I would try isolating your input element in a similar way, so that it's not deep in the DOM hierarchy. If the no results message is displayed, then you know it's CSS-related.
